tupla = ('Flamengo', 'Palmeiras', 'Botafogo', 'Atlético-MG', 'Grêmio', 'Athletico-PR', 'São Paulo', 'Internacional', 'Fortaleza', 'Bragantino', 'Cruzeiro', 'Cuiabá', 'Corinthians', 'Bahia', 'Vasco', 'Juventude', 'Vitória', 'Fluminense', 'Atlético-GO', 'Criciúma')
print('-=-'*86)
print('Lista de times do Brasileirão:\n', tupla)
print('-=-'*86)
print('Esses são os 5 primeiros colocados da tabela:\n',tupla[:5])
print('-=-'*86)
print('Esses são os ultimos 4 colocados da tabela:\n',tupla[-4:])
print('-=-'*86)
print('Times em ordem alfabetica:\n', sorted(tupla))
print('-=-'*86)
print('O juventude esta na {}ª posição...'.format(tupla.index('Juventude')+1))
print('-=-'*86)
